### ISSUE TITLE
qmd files opened in Jupyter Lab are destroyed if yaml is minimal

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/jupyterlab-quarto#14]
extension version 0.3.5
quarto version 1.5.57. Using this version because qmds won't open at all with 1.6. See previous issue on that.

On the second time I open any qmd file, all the text after the yaml is deleted. It doesn't matter what the yaml looks like.

Example, if I have a qmd file that has this yaml

```
---
title: The title
author: The authors
---

LOTS OF TEXT
```

When I open the qmd by in Jupyter Lab with Notebook or Jupytext Notebook, all the text after the yaml, like everything, is removed and the file is updated to look like with nothing after the yaml --- after I close and then re-open.  It does not happen if I open the qmd with editor.

```
---
title: The title
author: The authors
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.7
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---
```

* There is no warning that this is happening. All looks good when I save, but then the next time I open the file, all the text below the yaml is gone.
* The yaml doesn't have to be minimal. Same thing happens if I have the full yaml.
* Doesn't matter how the qmd file is created--in editor, in notebook in JLab, in RStudio.
